apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30081
